smtp_on: false
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: '456'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 30
smtp_username: jadhavpritam28@gmail.com
smtp_password: Lagibolala
smtp_from: jadhavpritam28@gmail.com
smtp_fromname: pritam
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
smtp_keepalive: false
_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
